# Generated by Django 3.1.3 on 2020-12-04 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_auto_20201203_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='subtotal',
            new_name='subtotal1',
        ),
    ]
