# Generated by Django 3.1.3 on 2020-12-04 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_auto_20201204_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='subtotal1',
            new_name='subtotal',
        ),
    ]
