# Generated by Django 3.0.6 on 2020-10-25 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_sno', models.IntegerField()),
                ('student_name', models.CharField(max_length=256)),
                ('student_father_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='student_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess2.student')),
            ],
        ),
    ]
